import { create } from "zustand";
import type { Resource, ResourceCategory } from "../types";

interface ResourceState {
    resources: Resource[];
    filters: {
        search: string;
        category: ResourceCategory | "all";
    };
    bookmarkedResources: string[];
    applications: string[];

    // Actions
    setSearch: (search: string) => void;
    setCategory: (category: ResourceCategory | "all") => void;
    fetchResources: () => void;
    applyToResource: (resourceId: string) => void;
    toggleBookmark: (resourceId: string) => void;
}

export const useResourceStore = create<ResourceState>((set) => ({
    resources: [],
    bookmarkedResources: [],
    applications: [],
    filters: {
        search: "",
        category: "all",
    },

    setSearch: (search) => set((state) => ({ filters: { ...state.filters, search } })),
    setCategory: (category) => set((state) => ({ filters: { ...state.filters, category } })),

    applyToResource: (resourceId) => set((state) => ({
        applications: state.applications.includes(resourceId)
            ? state.applications
            : [...state.applications, resourceId]
    })),

    toggleBookmark: (resourceId) => set((state) => ({
        bookmarkedResources: state.bookmarkedResources.includes(resourceId)
            ? state.bookmarkedResources.filter(id => id !== resourceId)
            : [...state.bookmarkedResources, resourceId]
    })),

    fetchResources: () => {
        // Comprehensive mock data for all 6 categories
        const mockResources: Resource[] = [
            // TENDERS (4 resources)
            {
                id: "T1",
                title: "Construction Material Supply Tender",
                company: "BuildPro Infrastructure",
                companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=BP&backgroundColor=7c3aed&fontFamily=Arial&fontWeight=700",
                location: "Mumbai, Maharashtra",
                compensation: "₹25L - ₹50L",
                type: "Contract",
                postedAt: "1 day ago",
                category: "Tenders",
                description: "We are inviting tenders for the supply of high-quality construction materials for our upcoming residential project in Mumbai. The selected vendor will be responsible for timely delivery and quality assurance.",
                requirements: [
                    "Valid GST registration and trade license",
                    "Minimum 3 years experience in construction material supply",
                    "Ability to supply materials worth ₹25L+ per month",
                    "Quality certifications (ISO 9001 preferred)",
                ],
                responsibilities: [
                    "Supply construction materials as per project specifications",
                    "Ensure timely delivery to project site",
                    "Maintain quality standards throughout the contract period",
                    "Provide necessary documentation and certifications",
                ],
                benefits: [
                    "Long-term contract opportunity",
                    "Timely payment within 30 days",
                    "Potential for future projects",
                    "Direct engagement with project management",
                ],
                duration: "12 months",
                urgency: "Within Week",
            },
            {
                id: "T2",
                title: "Road Development Project Tender",
                company: "State Highway Authority",
                companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=SHA&backgroundColor=7c3aed&fontFamily=Arial&fontWeight=700",
                location: "Pune, Maharashtra",
                compensation: "₹1Cr - ₹5Cr",
                type: "Project-based",
                postedAt: "3 days ago",
                category: "Tenders",
                description: "Tender for road development and maintenance project covering 25km stretch of state highway. Includes road widening, resurfacing, and drainage system installation.",
                requirements: [
                    "Class A contractor license",
                    "Previous experience in highway projects (minimum 5 years)",
                    "Equipment and machinery for road construction",
                    "Financial capability to handle ₹1Cr+ projects",
                ],
                responsibilities: [
                    "Complete road development as per technical specifications",
                    "Manage project timeline and milestones",
                    "Ensure quality control and safety standards",
                    "Submit progress reports and documentation",
                ],
                benefits: [
                    "Government project with assured payment",
                    "Performance-based incentives",
                    "Opportunity for future highway projects",
                    "Technical support from department",
                ],
                duration: "18 months",
                urgency: "Immediate",
            },
            {
                id: "T3",
                title: "IT Infrastructure Setup Tender",
                company: "TechCorp Solutions",
                companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=TC&backgroundColor=7c3aed&fontFamily=Arial&fontWeight=700",
                location: "Bangalore, Karnataka",
                compensation: "₹15L - ₹30L",
                type: "Contract",
                postedAt: "5 hours ago",
                category: "Tenders",
                description: "Tender for complete IT infrastructure setup including networking, servers, workstations, and security systems for our new office campus.",
                requirements: [
                    "Authorized dealer/partner of major IT brands",
                    "Minimum 2 years experience in enterprise IT setup",
                    "Technical team for installation and configuration",
                    "Post-installation support capability",
                ],
                responsibilities: [
                    "Procure and install IT equipment as per specifications",
                    "Configure network infrastructure and security systems",
                    "Provide training to IT staff",
                    "Offer 1-year warranty and support",
                ],
                benefits: [
                    "Single-window contract for entire setup",
                    "Milestone-based payments",
                    "AMC opportunity post-installation",
                    "Reference for future projects",
                ],
                duration: "6 months",
                urgency: "Within Week",
            },
            {
                id: "T4",
                title: "Catering Services Tender - Industrial Complex",
                company: "Mega Manufacturing Ltd",
                companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=MM&backgroundColor=7c3aed&fontFamily=Arial&fontWeight=700",
                location: "Ahmedabad, Gujarat",
                compensation: "₹8L - ₹12L per annum",
                type: "Contract",
                postedAt: "2 days ago",
                category: "Tenders",
                description: "Seeking catering service providers for our industrial complex serving 500+ employees daily. Must provide hygienic, nutritious meals for breakfast, lunch, and evening snacks.",
                requirements: [
                    "FSSAI license and health certifications",
                    "Experience in industrial/corporate catering (minimum 2 years)",
                    "Capacity to serve 500+ meals daily",
                    "Own kitchen setup and delivery vehicles",
                ],
                responsibilities: [
                    "Prepare and serve meals as per approved menu",
                    "Maintain hygiene and food safety standards",
                    "Manage kitchen staff and operations",
                    "Handle feedback and quality improvements",
                ],
                benefits: [
                    "Stable monthly revenue",
                    "Long-term contract with renewal option",
                    "Dedicated kitchen space provided",
                    "Timely payment guaranteed",
                ],
                duration: "24 months",
                urgency: "Flexible",
            },

            // LOGISTICS (4 resources)
            {
                id: "L1",
                title: "Interstate Freight Transportation",
                company: "LogiMove Express",
                companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=LM&backgroundColor=f97316&fontFamily=Arial&fontWeight=700",
                location: "Delhi NCR",
                compensation: "₹2,000 - ₹3,500 per trip",
                type: "Contract",
                postedAt: "6 hours ago",
                category: "Logistics",
                description: "Looking for reliable truck operators for interstate freight transportation. Regular routes between Delhi-Mumbai-Bangalore. Immediate joining for qualified drivers with own vehicles.",
                requirements: [
                    "Valid commercial driving license",
                    "Own truck (10-ton capacity minimum)",
                    "Minimum 3 years interstate driving experience",
                    "Clean driving record and insurance",
                ],
                responsibilities: [
                    "Transport goods safely between designated locations",
                    "Maintain delivery schedules and timelines",
                    "Handle loading and unloading supervision",
                    "Submit trip reports and documentation",
                ],
                benefits: [
                    "Guaranteed minimum trips per month",
                    "Fuel advance provided",
                    "Insurance coverage during transit",
                    "Performance bonuses",
                ],
                duration: "12 months",
                urgency: "Immediate",
            },
            {
                id: "L2",
                title: "Last-Mile Delivery Partners",
                company: "QuickShip Logistics",
                companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=QS&backgroundColor=f97316&fontFamily=Arial&fontWeight=700",
                location: "Bangalore, Karnataka",
                compensation: "₹25 - ₹40 per delivery",
                type: "Temporary",
                postedAt: "1 day ago",
                category: "Logistics",
                description: "Hiring delivery partners for last-mile e-commerce deliveries in Bangalore. Flexible hours, own two-wheeler required. Earn based on number of deliveries completed.",
                requirements: [
                    "Own two-wheeler with valid documents",
                    "Smartphone with GPS capability",
                    "Basic knowledge of Bangalore routes",
                    "Ability to handle 30-50 deliveries per day",
                ],
                responsibilities: [
                    "Pick up packages from warehouse/hub",
                    "Deliver to customers within assigned area",
                    "Collect payment for COD orders",
                    "Maintain delivery app and update status",
                ],
                benefits: [
                    "Flexible working hours",
                    "Weekly payouts",
                    "Fuel reimbursement",
                    "Incentives for high performance",
                ],
                urgency: "Within Week",
            },
            {
                id: "L3",
                title: "Warehouse Operations Manager",
                company: "StoreSafe Warehousing",
                companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=SS&backgroundColor=f97316&fontFamily=Arial&fontWeight=700",
                location: "Pune, Maharashtra",
                compensation: "₹40,000 - ₹60,000 per month",
                type: "Contract",
                postedAt: "4 days ago",
                category: "Logistics",
                description: "Seeking experienced warehouse operations manager to oversee inventory management, staff coordination, and logistics operations for our 50,000 sq ft facility.",
                requirements: [
                    "5+ years warehouse management experience",
                    "Knowledge of inventory management systems",
                    "Team handling experience (20+ staff)",
                    "Understanding of safety and compliance regulations",
                ],
                responsibilities: [
                    "Manage daily warehouse operations and staff",
                    "Oversee inventory accuracy and stock management",
                    "Coordinate with logistics and procurement teams",
                    "Ensure safety compliance and quality standards",
                ],
                benefits: [
                    "Competitive salary package",
                    "Performance-based bonuses",
                    "Health insurance coverage",
                    "Career growth opportunities",
                ],
                duration: "18 months",
                urgency: "Flexible",
            },
            {
                id: "L4",
                title: "Cold Chain Transportation Service",
                company: "FreshMove Logistics",
                companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=FM&backgroundColor=f97316&fontFamily=Arial&fontWeight=700",
                location: "Hyderabad, Telangana",
                compensation: "₹3,500 - ₹5,000 per trip",
                type: "Contract",
                postedAt: "12 hours ago",
                category: "Logistics",
                description: "Specialized cold chain transportation for perishable goods. Need refrigerated truck operators for pharmaceutical and food product delivery across South India.",
                requirements: [
                    "Refrigerated truck (reefer) with temperature control",
                    "Experience in cold chain logistics (minimum 2 years)",
                    "Understanding of temperature-sensitive cargo handling",
                    "Valid permits and certifications for food/pharma transport",
                ],
                responsibilities: [
                    "Maintain temperature-controlled environment during transit",
                    "Ensure timely delivery of perishable goods",
                    "Monitor and log temperature readings",
                    "Handle documentation and compliance requirements",
                ],
                benefits: [
                    "Premium rates for specialized service",
                    "Regular routes with guaranteed loads",
                    "Maintenance support for refrigeration units",
                    "Long-term partnership opportunity",
                ],
                duration: "24 months",
                urgency: "Immediate",
            },

            // EQUIPMENTS (4 resources)
            {
                id: "E1",
                title: "Excavator Rental - Construction Site",
                company: "BuildTech Developers",
                companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=BT&backgroundColor=10b981&fontFamily=Arial&fontWeight=700",
                location: "Noida, Uttar Pradesh",
                compensation: "₹8,000 - ₹12,000 per day",
                type: "Rental",
                postedAt: "2 days ago",
                category: "Equipments",
                description: "Need excavator with operator for foundation work at construction site. 3-month rental required for residential project. Must have experience in urban construction.",
                requirements: [
                    "20-ton excavator in good working condition",
                    "Experienced operator with valid license",
                    "Minimum 2 years construction site experience",
                    "Own maintenance and fuel arrangements",
                ],
                responsibilities: [
                    "Excavation work as per site requirements",
                    "Operate equipment safely following site protocols",
                    "Perform daily equipment checks and maintenance",
                    "Coordinate with site engineer for work planning",
                ],
                benefits: [
                    "Guaranteed daily rental for 3 months",
                    "Advance payment for first month",
                    "Accommodation for operator if needed",
                    "Extension possibility based on performance",
                ],
                duration: "3 months",
                urgency: "Within Week",
            },
            {
                id: "E2",
                title: "Tower Crane Operator Needed",
                company: "SkyHigh Constructions",
                companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=SH&backgroundColor=10b981&fontFamily=Arial&fontWeight=700",
                location: "Gurgaon, Haryana",
                compensation: "₹50,000 - ₹70,000 per month",
                type: "Contract",
                postedAt: "1 day ago",
                category: "Equipments",
                description: "Hiring certified tower crane operator for high-rise construction project. Must have experience operating tower cranes for buildings above 20 floors.",
                requirements: [
                    "Valid tower crane operator certification",
                    "Minimum 5 years high-rise construction experience",
                    "Knowledge of safety protocols and regulations",
                    "Ability to work at heights and in varying weather",
                ],
                responsibilities: [
                    "Operate tower crane for material lifting and placement",
                    "Coordinate with ground crew via radio communication",
                    "Conduct pre-operation safety checks",
                    "Maintain operation logs and reports",
                ],
                benefits: [
                    "Competitive monthly salary",
                    "Accommodation and food provided",
                    "Insurance coverage",
                    "Overtime pay for extra hours",
                ],
                duration: "18 months",
                urgency: "Immediate",
            },
            {
                id: "E3",
                title: "Concrete Mixer & Pump Equipment",
                company: "MixPro Equipment Rentals",
                companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=MP&backgroundColor=10b981&fontFamily=Arial&fontWeight=700",
                location: "Chennai, Tamil Nadu",
                compensation: "₹15,000 - ₹20,000 per day",
                type: "Rental",
                postedAt: "5 hours ago",
                category: "Equipments",
                description: "Looking for concrete mixer truck and pump equipment for commercial building project. Need equipment with experienced operators for continuous operation.",
                requirements: [
                    "Transit mixer (6-8 cubic meter capacity)",
                    "Concrete pump with 30m+ reach",
                    "Certified operators for both equipment",
                    "Equipment in excellent working condition",
                ],
                responsibilities: [
                    "Supply ready-mix concrete as per specifications",
                    "Pump concrete to designated locations",
                    "Maintain equipment and ensure zero downtime",
                    "Follow site safety and quality standards",
                ],
                benefits: [
                    "High daily rental rates",
                    "Guaranteed work for 6 months",
                    "Fuel cost reimbursement",
                    "Bonus for timely completion",
                ],
                duration: "6 months",
                urgency: "Immediate",
            },
            {
                id: "E4",
                title: "Generator Set Rental - Event Management",
                company: "PowerUp Events",
                companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=PU&backgroundColor=10b981&fontFamily=Arial&fontWeight=700",
                location: "Jaipur, Rajasthan",
                compensation: "₹5,000 - ₹8,000 per day",
                type: "Rental",
                postedAt: "3 days ago",
                category: "Equipments",
                description: "Need 100-150 KVA silent diesel generator sets for outdoor events and weddings. Multiple units required for peak season (October-March).",
                requirements: [
                    "Silent DG sets (100-150 KVA capacity)",
                    "Well-maintained with recent service records",
                    "Technician available for on-site support",
                    "Transportation arrangement for equipment",
                ],
                responsibilities: [
                    "Deliver and install generator at event venue",
                    "Ensure continuous power supply during event",
                    "Provide fuel and technical support",
                    "Dismantle and remove equipment post-event",
                ],
                benefits: [
                    "Multiple bookings during season",
                    "Advance booking calendar",
                    "Premium rates for peak dates",
                    "Long-term partnership for recurring events",
                ],
                urgency: "Flexible",
            },

            // VEHICLES (4 resources)
            {
                id: "V1",
                title: "Luxury Car Rental for Corporate",
                company: "EliteDrive Rentals",
                companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=ED&backgroundColor=3b82f6&fontFamily=Arial&fontWeight=700",
                location: "Mumbai, Maharashtra",
                compensation: "₹3,500 - ₹5,000 per day",
                type: "Rental",
                postedAt: "1 day ago",
                category: "Vehicles",
                description: "Looking for luxury sedan owners to partner for corporate car rental service. Vehicles will be used for airport transfers and business meetings. Professional chauffeur service preferred.",
                requirements: [
                    "Luxury sedan (BMW, Mercedes, Audi) 2020 or newer",
                    "Excellent vehicle condition with full service history",
                    "Professional chauffeur with clean driving record",
                    "Commercial vehicle permit and insurance",
                ],
                responsibilities: [
                    "Provide well-maintained luxury vehicle with driver",
                    "Ensure punctuality for corporate bookings",
                    "Maintain vehicle cleanliness and presentation",
                    "Follow professional service standards",
                ],
                benefits: [
                    "Guaranteed minimum bookings per month",
                    "Premium rental rates",
                    "Fuel and maintenance reimbursement",
                    "Long-term contract with corporate clients",
                ],
                duration: "12 months",
                urgency: "Within Week",
            },
            {
                id: "V2",
                title: "School Bus Driver - Morning & Evening Shifts",
                company: "Bright Future Academy",
                companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=BF&backgroundColor=3b82f6&fontFamily=Arial&fontWeight=700",
                location: "Bangalore, Karnataka",
                compensation: "₹25,000 - ₹35,000 per month",
                type: "Contract",
                postedAt: "4 days ago",
                category: "Vehicles",
                description: "Hiring experienced school bus drivers for student transportation. Must have clean driving record and experience with children. Two shifts: morning (6 AM - 9 AM) and evening (2 PM - 5 PM).",
                requirements: [
                    "Valid commercial driving license for heavy vehicles",
                    "Minimum 3 years bus driving experience",
                    "Police verification clearance",
                    "Patient and responsible attitude with children",
                ],
                responsibilities: [
                    "Pick up and drop students on designated routes",
                    "Ensure student safety during transit",
                    "Maintain bus cleanliness and basic maintenance",
                    "Follow traffic rules and school protocols",
                ],
                benefits: [
                    "Fixed monthly salary",
                    "Fuel and maintenance covered by school",
                    "Sundays and holidays off",
                    "Annual bonus and increment",
                ],
                duration: "12 months",
                urgency: "Immediate",
            },
            {
                id: "V3",
                title: "Tempo Traveller for Tourism",
                company: "WanderWheels Tours",
                companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=WW&backgroundColor=3b82f6&fontFamily=Arial&fontWeight=700",
                location: "Goa",
                compensation: "₹4,000 - ₹6,000 per day",
                type: "Rental",
                postedAt: "2 days ago",
                category: "Vehicles",
                description: "Need 12-17 seater tempo travellers for tourism packages. Peak season approaching, looking for well-maintained vehicles with experienced drivers for Goa sightseeing tours.",
                requirements: [
                    "Tempo Traveller (12-17 seater) in excellent condition",
                    "AC working, comfortable seating, music system",
                    "Driver with knowledge of Goa tourist spots",
                    "Valid tourist permit and insurance",
                ],
                responsibilities: [
                    "Provide vehicle for full-day/multi-day tours",
                    "Drive tourists to various destinations safely",
                    "Assist with luggage and basic tour guidance",
                    "Maintain vehicle cleanliness and comfort",
                ],
                benefits: [
                    "High season guaranteed bookings",
                    "Attractive daily rates",
                    "Fuel included in package",
                    "Tips and gratuities from tourists",
                ],
                duration: "6 months",
                urgency: "Within Week",
            },
            {
                id: "V4",
                title: "Ambulance Service Partnership",
                company: "LifeCare Medical Services",
                companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=LC&backgroundColor=3b82f6&fontFamily=Arial&fontWeight=700",
                location: "Delhi NCR",
                compensation: "₹2,000 - ₹3,500 per trip",
                type: "Contract",
                postedAt: "6 hours ago",
                category: "Vehicles",
                description: "Partnering with ambulance owners for emergency medical transportation. Must have basic life support equipment and trained paramedic. 24/7 availability required.",
                requirements: [
                    "Ambulance with BLS equipment (oxygen, stretcher, etc.)",
                    "Trained paramedic/EMT on board",
                    "Valid ambulance permit and medical equipment certification",
                    "24/7 availability for emergency calls",
                ],
                responsibilities: [
                    "Respond to emergency calls promptly",
                    "Provide basic life support during transit",
                    "Transport patients safely to hospitals",
                    "Maintain ambulance and medical equipment",
                ],
                benefits: [
                    "Per-trip payment plus monthly retainer",
                    "Tie-up with hospitals and insurance companies",
                    "Equipment maintenance support",
                    "Priority call allocation",
                ],
                duration: "24 months",
                urgency: "Immediate",
            },

            // PMC - Project Management Consultancy (3 resources)
            {
                id: "P1",
                title: "Infrastructure Project Manager",
                company: "MetroBuild Consultants",
                companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=MB&backgroundColor=6366f1&fontFamily=Arial&fontWeight=700",
                location: "Hyderabad, Telangana",
                compensation: "₹1.2L - ₹2L per month",
                type: "Contract",
                postedAt: "3 days ago",
                category: "PMC",
                description: "Seeking experienced project manager for metro rail infrastructure project. Will oversee civil works, contractor coordination, and timeline management for 15km elevated corridor construction.",
                requirements: [
                    "PMP or equivalent certification preferred",
                    "10+ years infrastructure project management experience",
                    "Knowledge of metro/railway construction standards",
                    "Strong stakeholder management skills",
                ],
                responsibilities: [
                    "Manage overall project execution and timelines",
                    "Coordinate with contractors, consultants, and authorities",
                    "Monitor quality, safety, and compliance",
                    "Prepare progress reports and presentations",
                ],
                benefits: [
                    "Prestigious metro rail project",
                    "Competitive compensation package",
                    "Performance-based incentives",
                    "Career advancement in infrastructure sector",
                ],
                duration: "36 months",
                urgency: "Within Week",
            },
            {
                id: "P2",
                title: "IT Project Consultant - Digital Transformation",
                company: "TechVision Consulting",
                companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=TV&backgroundColor=6366f1&fontFamily=Arial&fontWeight=700",
                location: "Pune, Maharashtra",
                compensation: "₹80,000 - ₹1.5L per month",
                type: "Contract",
                postedAt: "1 day ago",
                category: "PMC",
                description: "Looking for IT project consultant to lead digital transformation initiative for manufacturing client. Will manage ERP implementation, process automation, and change management.",
                requirements: [
                    "MBA or engineering degree with IT specialization",
                    "5+ years IT project consulting experience",
                    "Experience with ERP implementations (SAP/Oracle preferred)",
                    "Strong analytical and communication skills",
                ],
                responsibilities: [
                    "Lead digital transformation roadmap and execution",
                    "Manage ERP implementation and integration",
                    "Conduct process analysis and optimization",
                    "Train client teams and manage change",
                ],
                benefits: [
                    "Work with leading manufacturing company",
                    "Exposure to latest technologies",
                    "Flexible work arrangements",
                    "Opportunity for permanent role",
                ],
                duration: "18 months",
                urgency: "Immediate",
            },
            {
                id: "P3",
                title: "Real Estate Development PMC",
                company: "UrbanScape Developers",
                companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=US&backgroundColor=6366f1&fontFamily=Arial&fontWeight=700",
                location: "Gurgaon, Haryana",
                compensation: "₹1.5L - ₹2.5L per month",
                type: "Project-based",
                postedAt: "5 days ago",
                category: "PMC",
                description: "Project Management Consultancy required for mixed-use development project (residential + commercial). Will oversee design, approvals, construction, and delivery of 5-acre township.",
                requirements: [
                    "15+ years real estate project management experience",
                    "Knowledge of RERA, building codes, and approvals",
                    "Experience managing projects worth ₹500Cr+",
                    "Strong vendor and contractor network",
                ],
                responsibilities: [
                    "Manage end-to-end project lifecycle",
                    "Coordinate design, approvals, and construction",
                    "Control budget, timeline, and quality",
                    "Liaise with authorities and stakeholders",
                ],
                benefits: [
                    "Premium compensation package",
                    "Success-based performance bonus",
                    "Opportunity to shape landmark project",
                    "Equity participation option",
                ],
                duration: "48 months",
                urgency: "Flexible",
            },

            // CSM - Construction Supervision Management (3 resources)
            {
                id: "C1",
                title: "Site Supervisor - Residential Complex",
                company: "HomeBuild Constructions",
                companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=HB&backgroundColor=f43f5e&fontFamily=Arial&fontWeight=700",
                location: "Noida, Uttar Pradesh",
                compensation: "₹40,000 - ₹60,000 per month",
                type: "Contract",
                postedAt: "2 days ago",
                category: "CSM",
                description: "Need experienced site supervisor for 200-unit residential complex construction. Will supervise daily construction activities, labor management, and quality control.",
                requirements: [
                    "Diploma in Civil Engineering or equivalent",
                    "5+ years site supervision experience",
                    "Knowledge of construction methods and materials",
                    "Ability to read technical drawings and specifications",
                ],
                responsibilities: [
                    "Supervise daily construction activities and workers",
                    "Ensure work quality and adherence to drawings",
                    "Maintain site safety and housekeeping",
                    "Coordinate with contractors and material suppliers",
                ],
                benefits: [
                    "Competitive monthly salary",
                    "Accommodation near site",
                    "Performance incentives",
                    "Career growth in reputed company",
                ],
                duration: "24 months",
                urgency: "Immediate",
            },
            {
                id: "C2",
                title: "Quality Control Engineer - Bridge Construction",
                company: "BridgeTech Infrastructure",
                companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=BI&backgroundColor=f43f5e&fontFamily=Arial&fontWeight=700",
                location: "Kolkata, West Bengal",
                compensation: "₹60,000 - ₹90,000 per month",
                type: "Contract",
                postedAt: "4 days ago",
                category: "CSM",
                description: "Hiring quality control engineer for river bridge construction project. Will be responsible for testing, inspection, and quality assurance of all construction activities.",
                requirements: [
                    "B.Tech in Civil Engineering",
                    "3+ years QC experience in bridge/infrastructure projects",
                    "Knowledge of IS codes and quality testing procedures",
                    "Experience with concrete and steel testing",
                ],
                responsibilities: [
                    "Conduct quality tests and inspections",
                    "Review contractor work and approve quality",
                    "Maintain quality documentation and reports",
                    "Coordinate with third-party testing agencies",
                ],
                benefits: [
                    "Work on prestigious bridge project",
                    "Attractive compensation package",
                    "Exposure to advanced construction techniques",
                    "Certification and training opportunities",
                ],
                duration: "30 months",
                urgency: "Within Week",
            },
            {
                id: "C3",
                title: "Safety Officer - High-Rise Construction",
                company: "TowerPro Builders",
                companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=TP&backgroundColor=f43f5e&fontFamily=Arial&fontWeight=700",
                location: "Mumbai, Maharashtra",
                compensation: "₹50,000 - ₹75,000 per month",
                type: "Contract",
                postedAt: "1 day ago",
                category: "CSM",
                description: "Safety officer required for 40-floor high-rise construction. Will implement safety protocols, conduct training, and ensure compliance with safety regulations.",
                requirements: [
                    "NEBOSH/IOSH certification or equivalent",
                    "4+ years safety management in high-rise construction",
                    "Knowledge of safety laws and regulations",
                    "First aid and emergency response training",
                ],
                responsibilities: [
                    "Implement and monitor safety protocols",
                    "Conduct safety training and toolbox talks",
                    "Investigate incidents and prepare reports",
                    "Ensure PPE compliance and safety equipment availability",
                ],
                benefits: [
                    "Important role in worker safety",
                    "Competitive salary package",
                    "Insurance coverage",
                    "Professional development opportunities",
                ],
                duration: "36 months",
                urgency: "Immediate",
            },
        ];

        set({ resources: mockResources });
    },
}));
